from flask import Blueprint, render_template

views = Blueprint('views', __name__)

@views.route('/')
@views.route('/screener')
@views.route('/ipo')
@views.route('/ipo/upcoming')
@views.route('/ipo/ongoing')
@views.route('/ipo/closed')
@views.route('/ipo/mainboard')
@views.route('/ipo/sme')
@views.route('/gmp')
@views.route('/subscription')
@views.route('/allotment')
@views.route('/check-allotment')
@views.route('/check-allotment/bulk')
@views.route('/calendar')
@views.route('/calculator')
@views.route('/ipo/<slug>')
@views.route('/reviews')
@views.route('/blog')
@views.route('/blogs')
@views.route('/blog/<slug>')
@views.route('/blogs/<slug>')
@views.route('/watchlist')
@views.route('/admin')
def index_view(slug=None):
    return render_template('index.html')
